version: '3.7'

services:
  kepler_gu:
    volumes:
      - static:/static
    env_file:
      - .env.deploy
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
        - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "3232:5432"
    env_file:
      - .env.db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static:/static
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kepler_gu

  certbot: 
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email bptech@solcap.com.br --agree-tos --no-eff-email -d kepler.solcap.com.br 
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

volumes:
  static:
  postgres_data:

------WebKitFormBoundaryvr8xmlFT91lzBAag--
